### ISSUE TITLE
CIFAR weights

### ISSUE THREAD

**Issue by juancprzs** [HaozhiQi/ISONet#2]
Hi there. Thank you for the interesting paper.

I noticed that the implementation of the ISONet architecture includes the possibility of instantiating based on CIFAR's images' dimensions (as noted [here](https://github.com/HaozhiQi/ISONet/blob/master/isonet/models/isonet.py#L230)). However, I notice that the [Model Zoo](https://github.com/HaozhiQi/ISONet/blob/master/MODEL_ZOO.md) does not provide official weights for CIFAR. Are you planning on making these weights available?

Thank you

**Comment by HaozhiQi** [comment]
Hi @juancprzs,

Thanks for your interest.

That part is directly adopted from the original [pycls code](https://github.com/facebookresearch/pycls/blob/master/pycls/models/resnet.py) (acknowledged in the file header). For  ISONet on CIFAR, we didn't carefully explore the architecture & hyperparameter settings and do not report experiments in our paper. 

Currently, I don't have a plan to carefully train some models on CIFAR, but if you are interested, maybe the following config can be helpful as a baseline setting (ResNet110).

```
DATASET:
  NAME: CIFAR10
  NUM_CLASSES: 10
SOLVER:
  BASE_LR: 0.005
  LR_MILESTONES: [120, 240]
  MAX_EPOCHS: 300
  TRAIN_BATCH_SIZE: 128
  WARMUP: True
  WARMUP_EPOCH: 10
  WARMUP_FACTOR: 0.1
ISON:
  DEPTH: 110
  ORTHO_COEFF: 1e-4
  HAS_BN: False
  HAS_ST: False
  SReLU: True
```
